aj_user_user:
    resource: "@AJUserBundle/Resources/config/routes/user.yml"
    prefix:   /user

aj_task_task:
    resource: "@AJUserBundle/Resources/config/routes/task.yml"
    prefix:   /task
    
#Authentication
aj_user_homepage:
    path:     /
    defaults: { _controller: AJUserBundle:User:home }

aj_user_login:
    path:     /login
    defaults: { _controller: AJUserBundle:Security:login }

aj_user_login_check:
    path:     /login_check
    defaults: { _controller: AJUserBundle:Security:loginCheck }

aj_user_logout:
    path:     /logout