aj_task_index:
    path:     /index
    defaults: { _controller: AJUserBundle:Task:index }

aj_task_add:
    path:     /add
    defaults: { _controller: AJUserBundle:Task:add }

aj_task_create:
    path:     /create
    defaults: { _controller: AJUserBundle:Task:create }
    methods:  POST

aj_task_edit:
    path:     /edit/{id}
    defaults: { _controller: AJUserBundle:Task:edit }

aj_task_update:
    path:     /update/{id}
    defaults: { _controller: AJUserBundle:Task:update }
    methods:  [POST, PUT]

aj_task_view:
    path:     /view/{id}
    defaults: { _controller: AJUserBundle:Task:view }

aj_task_delete:
    path:     /delete/{id}
    defaults: { _controller: AJUserBundle:Task:delete }
    methods:  [POST, DELETE]

aj_task_redirect_add:
    path: /create
    defaults:
        _controller: AJUserBundle:Task:add
        path: /add
        permanent: true

aj_task_custom:
    path:     /custom
    defaults: { _controller: AJUserBundle:Task:custom }
    
aj_task_process:
    path:     /process/{id}
    defaults: { _controller: AJUserBundle:Task:process }
    methods:  [POST, PUT]    

aj_task_redirect_edit:
    path: /update/{id}
    defaults:
        _controller: AJUserBundle:Task:edit
        path: /edit/{id}
        permanent: true